"""follow up  migration

Revision ID: 58c8e8d644e6
Revises: 9fd2c15ef1eb
Create Date: 2024-04-05 13:56:13.239403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c8e8d644e6'
down_revision = '9fd2c15ef1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('magnitude', sa.Float(), nullable=True))
    op.add_column('earthquakes', sa.Column('location', sa.String(), nullable=True))
    op.add_column('earthquakes', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earthquakes', 'year')
    op.drop_column('earthquakes', 'location')
    op.drop_column('earthquakes', 'magnitude')
    # ### end Alembic commands ###
